# Generated by Django 4.1 on 2022-09-25 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_vistar_like_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vistar',
            new_name='postview',
        ),
    ]
